### ISSUE TITLE
Dark Mode Support ? 

### ISSUE THREAD

**Issue by Kewal89** [sidd2306/sidd2306.github.io#1]
**Please add dark mode support for this website sir. Big fan sir.** @sidd2306

**Comment by Kewal89** [comment]
Nic Ignore Sir. Bad customer support. I'll rate 1 *

**Comment by amogh-w** [comment]
Yes, sir, dark mode will greatly improve the aesthetics of your website!

**Comment by Kewal89** [comment]
Nic digga mode sir @sidd2306 . now i never wont my hurt eye at night coz very black mode website sir. big fan. rate i will at play store. 5 star all.
